services:
  - type: web
    name: taskpro-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: HELP_RECIPIENT_EMAIL
        sync: false
